# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
       # Add assignees
    assignees:
      - "clouddrove-ci"
# Add reviewer
    reviewers:
      - "approvers"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "_example/complete" # Location of package manifests
    schedule:
      interval: "weekly"
       # Add assignees
    assignees:
      - "clouddrove-ci"
       # Add reviewer
    reviewers:
      - "approvers"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "_example/cors_s3" # Location of package manifests
    schedule:
      interval: "weekly"
       # Add assignees
    assignees:
      - "clouddrove-ci"
       # Add reviewer
    reviewers:
      - "approvers"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "_example/default-s3" # Location of package manifests
    schedule:
      interval: "weekly"
       # Add assignees
    assignees:
      - "clouddrove-ci"
      # Add reviewer
    reviewers:
      - "approvers"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "_example/encryption-s3" # Location of package manifests
    schedule:
      interval: "weekly"
       # Add assignees
    assignees:
      - "clouddrove-ci"
      # Add reviewer
    reviewers:
      - "approvers"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "_example/logging-encryption-s3" # Location of package manifests
    schedule:
      interval: "weekly"
       # Add assignees
    assignees:
      - "clouddrove-ci"
      # Add reviewer
    reviewers:
      - "approvers"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "_example/logging-s3" # Location of package manifests
    schedule:
      interval: "weekly"
       # Add assignees
    assignees:
      - "clouddrove-ci"
      # Add reviewer
    reviewers:
      - "approvers"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "_example/s3-replication" # Location of package manifests
    schedule:
      interval: "weekly"
       # Add assignees
    assignees:
      - "clouddrove-ci"
      # Add reviewer
    reviewers:
      - "approvers"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "_example/website-s3" # Location of package manifests
    schedule:
      interval: "weekly"
       # Add assignees
    assignees:
      - "clouddrove-ci"
      # Add reviewer
    reviewers:
      - "approvers"